### ISSUE TITLE
charts that need to run on master nodes will need to add tolerations

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2-charts#107]
once https://github.com/samsung-cnct/k2/pull/588 is merged, any charts that need to run in the master nodepool will need to include tolerations for this master taint. 

example pod.yaml: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: {{.Values.name}}
  labels:
    app: log-gen
spec:
  containers:
    - name: log-gen
      image: {{.Values.image}}
      ports:
      - containerPort: 8080
    {{- if .Values.tolerations }}
  tolerations:
{{ toYaml .Values.tolerations | indent 4 }}
      {{- end}}
```

example values.yaml: 
```yaml

name: log-gen
image: quay.io/dstorck/log_app:latest
tolerations:
 - key: node-role.kubernetes.io/master
   operator: Equal
   effect: NoSchedule
 - operator: Exists
```
