### ISSUE TITLE
add option to charts for node affinity

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2-charts#113]
[example of values.yaml](https://github.com/venezia/chart-mongodb-replicaset/blob/90ceb11f62746b189d82f75c9f8d5a4251d42432/mongodb-replicaset/values.yaml#L19-L26)

[example of pod spec](https://github.com/venezia/chart-mongodb-replicaset/blob/90ceb11f62746b189d82f75c9f8d5a4251d42432/mongodb-replicaset/templates/mongodb-statefulset.yaml#L108-L126)

**Comment by DStorck** [comment]
proposed implementation is for each chart to add in to values.yaml something like:
```
scheduling:
  affinity:
    node:
      type: requiredDuringSchedulingIgnoredDuringExecution
      labels:
#      - key: iamalabelkey
#        operator: In
#        values: ["value1", "value2"]
``` 
and to the pod.yaml add in something like: 
```
    spec:
      {{- if .Values.scheduling.affinity }}
      {{- if .Values.scheduling.affinity.node }}
      {{- if .Values.scheduling.affinity.node.labels }}
      affinity:
        nodeAffinity:
          {{ .Values.scheduling.affinity.node.type }}:
            nodeSelectorTerms:
            - matchExpressions:
                {{- range .Values.scheduling.affinity.node.labels }}
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
                {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
```
